# Generated by Django 5.2.3 on 2025-06-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SinkholeIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="발생일시")),
                ("location", models.CharField(max_length=200, verbose_name="위치")),
                ("cause", models.TextField(blank=True, verbose_name="발생 원인")),
                (
                    "depth",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="깊이(m)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=100, verbose_name="자재명")),
                ("quantity", models.FloatField(verbose_name="수량")),
                (
                    "unit",
                    models.CharField(default="개", max_length=50, verbose_name="단위"),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="sinkhole.sinkholeincident",
                        verbose_name="관련 사고",
                    ),
                ),
            ],
        ),
    ]
